# Generated by Django 4.2.5 on 2023-10-01 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Amount must be more than 0')])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Price must be more than 0')])),
            ],
        ),
    ]
