# Generated by Django 3.2.16 on 2023-10-01 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_good_amount_alter_good_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Amount must be more than 0')]),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Price must be more than 0')]),
        ),
    ]
