# Generated by Django 3.2.16 on 2023-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20231001_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(),
        ),
    ]
