# Generated by Django 4.2.5 on 2023-10-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
