# Generated by Django 4.2.5 on 2023-10-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_token_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='used',
        ),
    ]
